name: Dependency Review
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: 'AtradiusGroup/atradius-advanced-security-configuration/review--einvoice.yml@main'
          external-repo-token: ${{ secrets.GH_ADV_SEC_TOKEN }}
